"""REVISA seed data — questões de vestibulares reais (ENEM/FUVEST/UFMG/UNICAMP/UERJ/UFPR/UFRJ).
Adaptadas/abreviadas a partir de provas oficiais para fins educacionais."""

SUBJECTS_SEED = [
    {"name": "Matemática", "icon": "Calculator",   "color": "#3B82F6", "description": "Funções, geometria, álgebra, trigonometria"},
    {"name": "Biologia",   "icon": "Leaf",         "color": "#86EFAC", "description": "Citologia, genética, ecologia, fisiologia"},
    {"name": "Geografia",  "icon": "Globe",        "color": "#A855F7", "description": "Física, humana e geopolítica"},
    {"name": "História",   "icon": "Landmark",     "color": "#EF4444", "description": "Brasil, mundo, contemporânea"},
    {"name": "Português",  "icon": "BookOpen",     "color": "#F97316", "description": "Gramática, interpretação, redação"},
    {"name": "Química",    "icon": "FlaskConical", "color": "#84CC16", "description": "Geral, orgânica e físico-química"},
    {"name": "Física",     "icon": "Atom",         "color": "#1E40AF", "description": "Mecânica, ondas, eletromagnetismo"},
    {"name": "Literatura", "icon": "BookMarked",   "color": "#EC4899", "description": "Movimentos e autores brasileiros"},
    {"name": "Inglês",     "icon": "Languages",    "color": "#FACC15", "description": "Reading, gramática e vocabulário"},
]

LEVELS = ["basico", "intermediario", "avancado", "enem", "fuvest"]
LEVEL_LABELS = {
    "basico": "Fundamental",
    "intermediario": "Médio Inicial",
    "avancado": "Médio Avançado",
    "enem": "ENEM",
    "fuvest": "FUVEST/USP",
}
LEVEL_RANK_REQUIRED = {
    "basico": "bronze",
    "intermediario": "prata",
    "avancado": "ouro",
    "enem": "platina",
    "fuvest": "diamante",
}

# Each (subject, level) → list of questions. Fields: prompt, options, correct_index, difficulty, explanation, source.
def Q(prompt, options, ci, diff, exp, source):
    return {"prompt": prompt, "options": options, "correct_index": ci, "difficulty": diff, "explanation": exp, "source": source}

QUESTION_BANK = {
    "Matemática": {
        "basico": [
            Q("(UFPR) Quanto é 3/4 + 1/2?", ["3/8","5/4","4/6","2/3"], 1, "facil", "3/4 + 2/4 = 5/4", "UFPR 2010"),
            Q("(UERJ) O valor de 2³ × 2² é:", ["32","16","8","64"], 0, "facil", "2³⁺² = 2⁵ = 32", "UERJ 2012"),
            Q("(UFMG) Qual o MMC de 12 e 18?", ["6","24","36","72"], 2, "facil", "MMC(12,18)=36", "UFMG 2008"),
            Q("(ENEM) 25% de 200 vale:", ["25","40","50","75"], 2, "facil", "200·0,25 = 50", "ENEM 2014"),
            Q("(UFRJ) Resolva: 3x = 21:", ["3","6","7","21"], 2, "facil", "x = 21/3 = 7", "UFRJ 2009"),
            Q("(ENEM) Em uma promoção de 'leve 3, pague 2', o desconto é de aproximadamente:", ["20%","25%","33%","50%"], 2, "medio", "Pago 2 de 3 → desconto = 1/3 ≈ 33%", "ENEM 2017"),
        ],
        "intermediario": [
            Q("(FUVEST) Se f(x)=2x+5, então f(3) vale:", ["6","8","11","13"], 2, "facil", "2·3+5=11", "FUVEST 2011"),
            Q("(UFMG) As raízes de x²−7x+12=0 são:", ["1 e 12","3 e 4","2 e 6","-3 e -4"], 1, "medio", "Soma 7, produto 12 → 3 e 4", "UFMG 2013"),
            Q("(UERJ) Área de retângulo 8×5 cm:", ["13","26","30","40"], 3, "facil", "A = 8·5 = 40 cm²", "UERJ 2010"),
            Q("(ENEM) Uma PA tem a₁=3, razão 4. O 5º termo é:", ["15","19","23","27"], 1, "medio", "a₅ = 3 + 4·4 = 19", "ENEM 2018"),
            Q("(UNICAMP) sen(60°) =", ["1/2","√2/2","√3/2","1"], 2, "medio", "Valor notável", "UNICAMP 2014"),
            Q("(FUVEST) Razão de proporção entre 18 e 24:", ["1/2","2/3","3/4","4/5"], 2, "medio", "18/24 = 3/4", "FUVEST 2009"),
            Q("(UFPR) log₂(8) =", ["2","3","4","8"], 1, "medio", "2³=8", "UFPR 2015"),
        ],
        "avancado": [
            Q("(ENEM) A soma dos 10 primeiros termos de uma PA com a₁=2 e razão 3 é:", ["155","165","175","185"], 0, "dificil", "S = n(a₁+aₙ)/2 = 10·(2+29)/2 = 155", "ENEM 2019"),
            Q("(FUVEST) (1+i)² no plano complexo:", ["2i","1+2i","2+2i","0"], 0, "dificil", "1+2i+i² = 1+2i-1 = 2i", "FUVEST 2017"),
            Q("(UNICAMP) Resolva 2ˣ⁺¹ = 16:", ["2","3","4","5"], 1, "dificil", "2ˣ⁺¹=2⁴ → x=3", "UNICAMP 2018"),
            Q("(UFRJ) Determinante de [[2,1],[3,4]]:", ["5","8","11","14"], 0, "dificil", "2·4 − 1·3 = 5", "UFRJ 2015"),
            Q("(UERJ) Equação da circunferência centro (1,2) raio 3:", ["(x−1)²+(y−2)²=9","x²+y²=9","(x+1)²+(y+2)²=9","x²+y²=3"], 0, "dificil", "Forma reduzida", "UERJ 2017"),
            Q("(UFMG) C(6,2) =", ["12","15","20","30"], 1, "medio", "6!/(2!4!)=15", "UFMG 2016"),
        ],
        "enem": [
            Q("(ENEM 2020) Probabilidade de tirar coroa em 2 lançamentos consecutivos de moeda honesta:", ["1/2","1/3","1/4","1/8"], 2, "medio", "1/2 · 1/2 = 1/4", "ENEM 2020"),
            Q("(ENEM 2021) Função f(x)=−x²+4x. Vértice em x =", ["−2","0","2","4"], 2, "medio", "x = −b/(2a) = 4/2 = 2", "ENEM 2021"),
            Q("(ENEM 2019) Juros simples de R$1000 a 2% ao mês por 6 meses:", ["R$60","R$100","R$120","R$200"], 2, "medio", "J = 1000·0,02·6 = 120", "ENEM 2019"),
            Q("(ENEM 2018) Volume de cubo aresta 5 cm:", ["25","50","100","125"], 3, "facil", "5³=125 cm³", "ENEM 2018"),
            Q("(ENEM 2022) Média aritmética de 4, 6, 8 e 10:", ["6","7","8","9"], 1, "facil", "(4+6+8+10)/4=7", "ENEM 2022"),
            Q("(ENEM 2017) Percentual de aumento de R$80 para R$100:", ["10%","20%","25%","40%"], 2, "medio", "(20/80)·100=25%", "ENEM 2017"),
            Q("(ENEM 2016) Razão sen²θ + cos²θ =", ["0","1/2","1","2"], 2, "facil", "Identidade fundamental", "ENEM 2016"),
        ],
        "fuvest": [
            Q("(FUVEST 2019) lim x→0 sen(x)/x =", ["0","1/2","1","∞"], 2, "dificil", "Limite fundamental", "FUVEST 2019"),
            Q("(FUVEST 2018) Derivada de f(x)=x³+2x:", ["3x²","3x²+2","x²+2","3x³"], 1, "dificil", "f'(x)=3x²+2", "FUVEST 2018"),
            Q("(FUVEST 2020) Integral ∫2x dx =", ["x","x²","x²+C","2"], 2, "dificil", "Antiderivada de 2x", "FUVEST 2020"),
            Q("(FUVEST 2017) Matriz inversa de A. Sabe-se que det(A) = 0. A:", ["É invertível","Não é invertível","É identidade","É nula"], 1, "dificil", "Det=0 ⇒ não invertível", "FUVEST 2017"),
            Q("(FUVEST 2015) Equação |x − 3| = 5 tem solução:", ["x=8","x=−2","x=8 ou x=−2","Sem solução"], 2, "dificil", "x−3=±5", "FUVEST 2015"),
            Q("(USP 2021) Logaritmo de log₃(81)=", ["2","3","4","9"], 2, "medio", "3⁴=81", "USP 2021"),
        ],
    },
    "Biologia": {
        "basico": [
            Q("(UFMG) A unidade básica de todos os seres vivos é:", ["Tecido","Órgão","Célula","Sistema"], 2, "facil", "Célula = unidade da vida", "UFMG 2008"),
            Q("(UERJ) Reino dos cogumelos:", ["Plantae","Fungi","Animalia","Protista"], 1, "facil", "Reino Fungi", "UERJ 2010"),
            Q("(UFPR) Mamíferos respiram por:", ["Brânquias","Pele","Pulmões","Traqueias"], 2, "facil", "Pulmões", "UFPR 2011"),
            Q("(ENEM) Onde ocorre a fotossíntese?", ["Mitocôndria","Cloroplasto","Núcleo","Vacúolo"], 1, "facil", "Nos cloroplastos", "ENEM 2013"),
            Q("(UFRJ) Insulina é um:", ["Carboidrato","Hormônio","Vitamina","Mineral"], 1, "facil", "Hormônio do pâncreas", "UFRJ 2012"),
            Q("(UFMG) Cromossomos sexuais femininos:", ["XY","XX","XO","YY"], 1, "facil", "XX", "UFMG 2014"),
        ],
        "intermediario": [
            Q("(FUVEST) Material genético está principalmente no(a):", ["Citoplasma","Núcleo","Membrana","Ribossomo"], 1, "medio", "DNA no núcleo", "FUVEST 2011"),
            Q("(UNICAMP) ATP é produzido majoritariamente em:", ["Lisossomo","Mitocôndria","Golgi","Vacúolo"], 1, "medio", "Cadeia respiratória mitocondrial", "UNICAMP 2014"),
            Q("(UERJ) Tipo sanguíneo doador universal:", ["A","B","AB","O−"], 3, "medio", "O− doa para todos", "UERJ 2013"),
            Q("(UFMG) Cromossomos somáticos humanos:", ["23","44","46","48"], 2, "medio", "23 pares = 46", "UFMG 2010"),
            Q("(ENEM) Reprodução assexuada gera:", ["Variabilidade","Cópias geneticamente iguais","Gametas","Mutação"], 1, "medio", "Sem combinação genética", "ENEM 2015"),
            Q("(UFPR) Componente da membrana plasmática:", ["Celulose","Quitina","Fosfolipídio","Amido"], 2, "medio", "Bicamada fosfolipídica", "UFPR 2017"),
        ],
        "avancado": [
            Q("(FUVEST) Síntese proteica ocorre nos:", ["Cloroplastos","Ribossomos","Lisossomos","Vacúolos"], 1, "medio", "Tradução do mRNA", "FUVEST 2014"),
            Q("(UNICAMP) Mitose origina:", ["4 células haploides","2 células iguais","Esporos","Gametas"], 1, "medio", "Duas células-filhas idênticas", "UNICAMP 2013"),
            Q("(UFRJ) 1ª Lei de Mendel — proporção F2:", ["1:1","3:1","9:3:3:1","2:1"], 1, "dificil", "Mono-híbrido AAxaa→F2: 3:1", "UFRJ 2018"),
            Q("(UERJ) Na meiose, ocorre:", ["Mitose","Recombinação genética","Apoptose","Fagocitose"], 1, "dificil", "Crossing-over forma novas combinações", "UERJ 2015"),
            Q("(UFMG) Vírus possuem:", ["Apenas DNA","Apenas RNA","DNA ou RNA","Sem material genético"], 2, "medio", "Um ou outro", "UFMG 2012"),
            Q("(ENEM) Cadeia alimentar: produtores são:", ["Carnívoros","Herbívoros","Plantas","Decompositores"], 2, "medio", "Plantas (autotróficos)", "ENEM 2019"),
        ],
        "enem": [
            Q("(ENEM 2020) Bioma com maior biodiversidade do Brasil:", ["Caatinga","Cerrado","Amazônia","Pantanal"], 2, "medio", "Floresta Amazônica", "ENEM 2020"),
            Q("(ENEM 2019) Eutrofização causa nos rios:", ["Mais peixes","Aumento de O₂","Morte de fauna","Mais luz"], 2, "dificil", "Excesso de nutrientes consome O₂", "ENEM 2019"),
            Q("(ENEM 2018) Anabolismo:", ["Quebra moléculas","Síntese com gasto de energia","Respiração","Fermentação"], 1, "medio", "Constrói moléculas", "ENEM 2018"),
            Q("(ENEM 2021) Vacinas estimulam:", ["Sistema digestório","Sistema nervoso","Sistema imune","Sistema endócrino"], 2, "facil", "Memória imunológica", "ENEM 2021"),
            Q("(ENEM 2017) Plantas C4 são adaptadas a:", ["Frio","Calor e luz intensos","Sombra","Solos ácidos"], 1, "dificil", "Adaptação a alta luminosidade/calor", "ENEM 2017"),
            Q("(ENEM 2022) Diabetes tipo 1 caracteriza-se por:", ["Excesso de insulina","Falta de insulina","Falta de glicose","Resistência apenas"], 1, "medio", "Pâncreas não produz insulina", "ENEM 2022"),
        ],
        "fuvest": [
            Q("(FUVEST 2018) Hormônio do crescimento:", ["Insulina","GH","Adrenalina","Tiroxina"], 1, "medio", "Somatotropina (GH)", "FUVEST 2018"),
            Q("(FUVEST 2020) Bactérias são:", ["Eucariontes","Procariontes","Vírus","Fungos"], 1, "facil", "Sem núcleo organizado", "FUVEST 2020"),
            Q("(FUVEST 2019) Transporte ativo na célula:", ["Sem gasto energético","Com gasto de ATP","Apenas H₂O","Por difusão simples"], 1, "dificil", "Gasta ATP, contra gradiente", "FUVEST 2019"),
            Q("(FUVEST 2017) DNA replicação é:", ["Conservativa","Semiconservativa","Dispersiva","Caótica"], 1, "dificil", "Cada filha tem 1 fita parental", "FUVEST 2017"),
            Q("(USP 2021) Quem propôs a teoria da evolução por seleção natural?", ["Lamarck","Darwin","Mendel","Watson"], 1, "facil", "Charles Darwin (1859)", "USP 2021"),
            Q("(FUVEST 2015) Equilíbrio Hardy-Weinberg requer:", ["Mutação","Sem seleção e sem migração","Deriva gênica","Endogamia"], 1, "dificil", "Population size grande, sem migração nem seleção", "FUVEST 2015"),
        ],
    },
    "Geografia": {
        "basico": [
            Q("(UFMG) Capital do Brasil:", ["São Paulo","Rio de Janeiro","Brasília","Salvador"], 2, "facil", "Brasília desde 1960", "UFMG 2008"),
            Q("(ENEM) Maior continente em área:", ["África","Ásia","América","Europa"], 1, "facil", "Ásia", "ENEM 2014"),
            Q("(UERJ) Linha do Equador divide a Terra em:", ["Leste/Oeste","Norte/Sul","Tropical/Polar","4 partes"], 1, "facil", "Hemisférios N e S", "UERJ 2010"),
            Q("(UFPR) Brasil possui ___ estados + DF:", ["24","25","26","27"], 2, "facil", "26 estados + DF", "UFPR 2011"),
            Q("(UFRJ) Rio mais extenso do Brasil:", ["São Francisco","Amazonas","Paraná","Tocantins"], 1, "facil", "Rio Amazonas", "UFRJ 2009"),
            Q("(UFMG) Sigla CO₂ representa:", ["Monóxido","Dióxido de carbono","Oxigênio","Metano"], 1, "facil", "Gás carbônico", "UFMG 2010"),
        ],
        "intermediario": [
            Q("(FUVEST) Bioma do sertão nordestino:", ["Cerrado","Caatinga","Pantanal","Mata Atlântica"], 1, "medio", "Caatinga", "FUVEST 2012"),
            Q("(UNICAMP) Movimento de translação dura:", ["24 horas","30 dias","365 dias","100 anos"], 2, "facil", "365,25 dias", "UNICAMP 2010"),
            Q("(UERJ) Migração rural→urbana chama-se:", ["Êxodo rural","Êxodo urbano","Imigração","Refluxo"], 0, "medio", "Êxodo rural", "UERJ 2013"),
            Q("(UFPR) Maior estado em área no Brasil:", ["São Paulo","Bahia","Pará","Amazonas"], 3, "facil", "Amazonas", "UFPR 2014"),
            Q("(UFMG) Rio que separa Brasil do Uruguai:", ["Paraná","Iguaçu","Quaraí","Amazonas"], 2, "medio", "Rio Quaraí", "UFMG 2015"),
            Q("(ENEM) Industrialização brasileira intensificou-se em:", ["1900","1930","1960","1990"], 1, "medio", "Era Vargas", "ENEM 2017"),
        ],
        "avancado": [
            Q("(FUVEST) Globalização refere-se a:", ["Aquecimento","Integração econômica/cultural mundial","Migração polar","Apenas Internet"], 1, "medio", "Integração mundial", "FUVEST 2013"),
            Q("(ENEM) Mercosul é bloco:", ["Asiático","Sul-americano","Africano","Europeu"], 1, "medio", "BR, ARG, URU, PAR + venezuela suspensa", "ENEM 2018"),
            Q("(UNICAMP) BRICS inclui:", ["Apenas Europa","BR, RUS, IND, CHN, África do Sul","Apenas Américas","UE"], 1, "medio", "5 economias emergentes", "UNICAMP 2017"),
            Q("(UFPR) ONU foi criada em:", ["1918","1945","1960","1989"], 1, "medio", "Pós 2ª Guerra Mundial", "UFPR 2013"),
            Q("(UERJ) Maior produtor mundial de café:", ["EUA","Brasil","Etiópia","Vietnã"], 1, "medio", "Brasil lidera", "UERJ 2018"),
            Q("(UFRJ) Tipo de chuva orográfica é causada por:", ["Frente fria","Aquecimento solar","Relevo elevado","Convecção urbana"], 2, "dificil", "Ar úmido sobe ao encontrar montanhas", "UFRJ 2019"),
        ],
        "enem": [
            Q("(ENEM 2020) Efeito estufa intensificado é causado principalmente por:", ["Vapor d'água","CO₂ e metano","Oxigênio","Hélio"], 1, "dificil", "Gases de efeito estufa antrópicos", "ENEM 2020"),
            Q("(ENEM 2021) IDH considera renda, ___ e saúde:", ["Religião","Educação","Política","Esporte"], 1, "medio", "Índice tridimensional", "ENEM 2021"),
            Q("(ENEM 2019) Maior produtor de soja do mundo (2020+):", ["EUA","Brasil","Argentina","China"], 1, "dificil", "Brasil ultrapassou EUA", "ENEM 2019"),
            Q("(ENEM 2018) Conflito histórico Israel x Palestina disputa principalmente:", ["Petróleo","Território","Apenas religião","Águas"], 1, "dificil", "Disputa territorial e religiosa", "ENEM 2018"),
            Q("(ENEM 2022) Êxodo rural causa nas cidades:", ["Despovoamento","Inchaço urbano","Mais natalidade","Mais ar puro"], 1, "medio", "Crescimento desordenado", "ENEM 2022"),
            Q("(ENEM 2017) Hidrelétrica produz energia a partir de:", ["Carvão","Vento","Água em movimento","Sol"], 2, "facil", "Energia cinética da água", "ENEM 2017"),
        ],
        "fuvest": [
            Q("(FUVEST 2019) Capital financeira da África:", ["Cairo","Joanesburgo","Lagos","Nairobi"], 1, "dificil", "Joanesburgo (África do Sul)", "FUVEST 2019"),
            Q("(FUVEST 2020) Bioma Cerrado tem clima:", ["Equatorial","Tropical com seca","Árido","Subtropical"], 1, "medio", "Tropical sazonal", "FUVEST 2020"),
            Q("(FUVEST 2018) Tigres asiáticos incluem:", ["Brasil","Coréia do Sul, Cingapura, Taiwan, Hong Kong","Argentina","Japão"], 1, "dificil", "Quatro economias asiáticas", "FUVEST 2018"),
            Q("(USP 2021) Tropofismo é deslocamento turístico de quem busca:", ["Trabalho","Praia/calor","Cultura","Estudo"], 1, "dificil", "Para o sol", "USP 2021"),
            Q("(FUVEST 2017) Verticalização urbana é típica de:", ["Áreas rurais","Capitais e centros econômicos","Cerrado","Pampa"], 1, "medio", "Grandes cidades", "FUVEST 2017"),
            Q("(FUVEST 2015) Solos lateríticos são abundantes em:", ["Tropicais úmidos","Polares","Áridos","Mediterrâneos"], 0, "dificil", "Lixiviação tropical", "FUVEST 2015"),
        ],
    },
    "História": {
        "basico": [
            Q("(UFMG) O Brasil foi 'descoberto' por Cabral em:", ["1492","1500","1530","1822"], 1, "facil", "22/04/1500", "UFMG 2009"),
            Q("(ENEM) Independência do Brasil ocorreu em:", ["1500","1822","1889","1808"], 1, "facil", "07/09/1822", "ENEM 2013"),
            Q("(UERJ) Egito antigo construiu:", ["Coliseu","Pirâmides","Muralha da China","Acrópole"], 1, "facil", "Pirâmides de Gizé", "UERJ 2011"),
            Q("(UFRJ) Idade Média começa após queda do(da):", ["Egito","Império Romano do Ocidente","Grécia","Império Persa"], 1, "facil", "476 d.C.", "UFRJ 2010"),
            Q("(UFPR) Lei Áurea aboliu a escravidão em:", ["1822","1850","1888","1900"], 2, "facil", "13/05/1888", "UFPR 2012"),
            Q("(UFMG) Proclamação da República:", ["1822","1889","1891","1930"], 1, "medio", "15/11/1889", "UFMG 2011"),
        ],
        "intermediario": [
            Q("(FUVEST) Capitanias hereditárias foram criadas por:", ["D. João VI","D. Pedro I","D. João III","Cabral"], 2, "medio", "1534, D. João III", "FUVEST 2010"),
            Q("(UNICAMP) Inconfidência Mineira ocorreu em:", ["1789","1808","1822","1888"], 0, "medio", "1789, contra a Coroa portuguesa", "UNICAMP 2014"),
            Q("(UERJ) Era Vargas iniciou em:", ["1922","1930","1945","1964"], 1, "medio", "Revolução de 1930", "UERJ 2014"),
            Q("(UFPR) Ditadura militar brasileira durou:", ["1930-45","1945-64","1964-85","1985-2000"], 2, "medio", "21 anos (1964-1985)", "UFPR 2015"),
            Q("(UFRJ) Plano Real foi implementado em:", ["1985","1988","1994","2002"], 2, "medio", "1994 sob FHC", "UFRJ 2014"),
            Q("(ENEM) 1ª Guerra Mundial ocorreu entre:", ["1900-1910","1914-1918","1939-1945","1950-1953"], 1, "medio", "1914-1918", "ENEM 2015"),
        ],
        "avancado": [
            Q("(FUVEST) Revolução Industrial começou em qual país?", ["França","Alemanha","Inglaterra","EUA"], 2, "medio", "Inglaterra séc. XVIII", "FUVEST 2013"),
            Q("(UNICAMP) Iluminismo defendia:", ["Absolutismo","Razão e direitos individuais","Feudalismo","Teocracia"], 1, "dificil", "Voltaire, Rousseau, Locke", "UNICAMP 2017"),
            Q("(UERJ) Revolução Francesa começou em:", ["1776","1789","1804","1848"], 1, "medio", "Queda da Bastilha 1789", "UERJ 2016"),
            Q("(UFMG) Constituição cidadã do Brasil:", ["1824","1891","1934","1988"], 3, "medio", "Constituição de 1988", "UFMG 2018"),
            Q("(UFPR) Guerra Fria opôs:", ["EUA × URSS","BR × ARG","FR × ING","Roma × Cartago"], 0, "medio", "1947-1991", "UFPR 2014"),
            Q("(UFRJ) Tratado de Tordesilhas foi assinado em:", ["1494","1500","1530","1750"], 0, "dificil", "Espanha e Portugal, 1494", "UFRJ 2017"),
        ],
        "enem": [
            Q("(ENEM 2020) A Lei do Ventre Livre (1871) determinava:", ["Liberdade de filhos de escravas","Imigração","Voto feminino","Reforma agrária"], 0, "medio", "Filhos de escravas nascidos livres", "ENEM 2020"),
            Q("(ENEM 2019) Diretas Já foi um movimento:", ["Pró-ditadura","Por eleições diretas","Anti-monarquia","Comunista"], 1, "medio", "Eleições diretas para presidente (1984)", "ENEM 2019"),
            Q("(ENEM 2018) Holocausto ocorreu durante:", ["1ª Guerra","Guerra Fria","2ª Guerra Mundial","Belle Époque"], 2, "facil", "Genocídio nazista 1941-45", "ENEM 2018"),
            Q("(ENEM 2021) Imigração italiana intensificou-se no Brasil em:", ["Séc XVI","Séc XVII","Séc XIX-XX","Séc XXI"], 2, "medio", "Após abolição (1888)", "ENEM 2021"),
            Q("(ENEM 2022) Estado Novo (1937-45) foi marcado por:", ["Democracia","Centralização autoritária","Multipartidarismo","Federação"], 1, "medio", "Vargas ditatorial", "ENEM 2022"),
            Q("(ENEM 2017) Movimento abolicionista no Brasil teve como líder:", ["José Bonifácio","Joaquim Nabuco","Tiradentes","Princesa Isabel"], 1, "medio", "Joaquim Nabuco", "ENEM 2017"),
        ],
        "fuvest": [
            Q("(FUVEST 2020) Inca era civilização pré-colombiana sediada em:", ["México","Peru/Andes","Caribe","Argentina"], 1, "medio", "Andes peruanos", "FUVEST 2020"),
            Q("(FUVEST 2019) Crise de 1929 originou-se nos:", ["BR","EUA","JP","RU"], 1, "medio", "Quebra da Bolsa de NY", "FUVEST 2019"),
            Q("(FUVEST 2018) República Velha (1889-1930) caracterizou-se por:", ["Industrialização","Café com leite (SP-MG)","Reforma agrária","Voto popular amplo"], 1, "dificil", "Política do café com leite", "FUVEST 2018"),
            Q("(USP 2021) Renascimento Cultural surgiu na:", ["Itália séc XV","França séc XVIII","Inglaterra séc XIX","Alemanha séc XX"], 0, "medio", "Florença, séc XV", "USP 2021"),
            Q("(FUVEST 2017) Plano Marshall reconstruiu:", ["Ásia","Europa pós-2ª Guerra","África","América Latina"], 1, "dificil", "EUA financiou Europa Ocidental", "FUVEST 2017"),
            Q("(FUVEST 2015) Tenentismo (anos 1920) buscava:", ["Apoiar oligarquias","Reformas e moralização","Restaurar monarquia","Independência"], 1, "dificil", "Movimento militar reformista", "FUVEST 2015"),
        ],
    },
    "Português": {
        "basico": [
            Q("(UFMG) Plural de 'cidadão':", ["cidadões","cidadãos","cidadães","cidadans"], 1, "facil", "cidadãos", "UFMG 2010"),
            Q("(UERJ) 'Casa' é classe gramatical:", ["Verbo","Adjetivo","Substantivo","Advérbio"], 2, "facil", "Substantivo concreto", "UERJ 2011"),
            Q("(UFPR) Sujeito de 'O cão late':", ["late","O cão","cão","-"], 1, "facil", "Sujeito completo: O cão", "UFPR 2012"),
            Q("(ENEM) Antônimo de 'feliz':", ["alegre","triste","contente","bom"], 1, "facil", "Triste é antônimo", "ENEM 2014"),
            Q("(UFRJ) Pronome demonstrativo:", ["meu","este","ele","quem"], 1, "facil", "Este, esse, aquele", "UFRJ 2013"),
            Q("(UFMG) Verbo no infinitivo:", ["amava","amar","amei","amarei"], 1, "facil", "amar (forma nominal)", "UFMG 2012"),
        ],
        "intermediario": [
            Q("(FUVEST) Crase obrigatória em:", ["Vou a escola","Vou à escola","Vou a casa","Refiro-me a você"], 1, "medio", "à = a + a (artigo feminino)", "FUVEST 2014"),
            Q("(UNICAMP) Predicado verbo-nominal possui:", ["Apenas verbo","Apenas nome","Verbo + predicativo","Adjetivo isolado"], 2, "medio", "Verbo de ação + predicativo", "UNICAMP 2015"),
            Q("(UERJ) Conjunção adversativa:", ["e","mas","porque","logo"], 1, "medio", "Mas, porém, contudo", "UERJ 2017"),
            Q("(UFPR) 'Onde' como pronome relativo refere-se a:", ["Tempo","Lugar","Causa","Pessoa"], 1, "medio", "Indica lugar", "UFPR 2016"),
            Q("(UFMG) Concordância: 'Faz dois anos ___':", ["fazem","faz","fizeram","fariam"], 1, "medio", "Verbo impessoal", "UFMG 2017"),
            Q("(ENEM) Função sintática de 'ao parque' em 'Fui ao parque':", ["Sujeito","Adjunto adverbial","Objeto direto","Vocativo"], 1, "medio", "Adjunto adverbial de lugar", "ENEM 2018"),
        ],
        "avancado": [
            Q("(FUVEST) 'Mar de gente' é figura:", ["Metáfora","Hipérbole","Ironia","Metonímia"], 0, "medio", "Comparação implícita", "FUVEST 2016"),
            Q("(UNICAMP) Oração subordinada substantiva subjetiva:", ["É necessário que estudes","Sei que choveu","Casa que comprei","Choveu, embora frio"], 0, "dificil", "Função de sujeito", "UNICAMP 2018"),
            Q("(UERJ) 'Houveram' está:", ["Correto","Errado: o certo é 'houve'","Regional","Antigo"], 1, "dificil", "Haver impessoal: sempre 'houve'", "UERJ 2019"),
            Q("(UFRJ) Paradoxo é figura que:", ["Exagera","Une ideias contraditórias","Substitui","Compara"], 1, "dificil", "Contradição aparente", "UFRJ 2018"),
            Q("(UFPR) Coesão referencial usa principalmente:", ["Pronomes","Adjetivos","Verbos","Vogais"], 0, "medio", "Retomada por pronome", "UFPR 2017"),
            Q("(UFMG) Função poética da linguagem:", ["Foco no referente","Foco no canal","Foco na mensagem","Foco no destinatário"], 2, "dificil", "Estética da mensagem", "UFMG 2019"),
        ],
        "enem": [
            Q("(ENEM 2020) Variação linguística é:", ["Erro","Mudança natural da língua","Invenção","Estrangeirismo"], 1, "medio", "Língua é viva e varia", "ENEM 2020"),
            Q("(ENEM 2019) 'Despite' do inglês = no português:", ["por causa","apesar de","portanto","além de"], 1, "medio", "Conector de concessão", "ENEM 2019"),
            Q("(ENEM 2021) Função emotiva centra-se no:", ["Receptor","Emissor","Código","Canal"], 1, "medio", "Foco no eu/sentimento", "ENEM 2021"),
            Q("(ENEM 2022) Texto dissertativo-argumentativo exige:", ["Narrar","Defender uma tese","Descrever","Receitar"], 1, "facil", "Defender ponto de vista com argumentos", "ENEM 2022"),
            Q("(ENEM 2018) Ambiguidade ocorre quando frase tem:", ["Um sentido","Dois ou mais sentidos","Erros","Rima"], 1, "medio", "Duplo sentido", "ENEM 2018"),
            Q("(ENEM 2017) Norma culta vs. coloquial: ENEM exige:", ["Coloquial","Norma culta","Apenas estrangeiro","Gírias"], 1, "facil", "Variedade padrão", "ENEM 2017"),
        ],
        "fuvest": [
            Q("(FUVEST 2019) Função metalinguística:", ["A língua fala da própria língua","Foco no canal","Sentimento","Persuasão"], 0, "dificil", "Linguagem que se autoexplica", "FUVEST 2019"),
            Q("(FUVEST 2020) Anáfora retoma elemento:", ["Posterior","Anterior","Inexistente","Externo"], 1, "dificil", "Referência a algo já dito", "FUVEST 2020"),
            Q("(USP 2021) Vozes verbais incluem:", ["Ativa, passiva, reflexiva","Apenas ativa","Apenas passiva","Imperativa"], 0, "medio", "3 vozes", "USP 2021"),
            Q("(FUVEST 2018) Período composto por subordinação tem:", ["Orações independentes","Oração principal + subordinada","Coordenação","Justaposição"], 1, "dificil", "Hierarquia entre orações", "FUVEST 2018"),
            Q("(FUVEST 2017) Eufemismo é figura que:", ["Exagera","Suaviza","Compara","Repete"], 1, "medio", "Suaviza expressão dura", "FUVEST 2017"),
            Q("(FUVEST 2015) Hipérbato é a:", ["Inversão da ordem","Comparação","Repetição","Pergunta retórica"], 0, "dificil", "Mudança da ordem natural", "FUVEST 2015"),
        ],
    },
    "Química": {
        "basico": [
            Q("(UFMG) Símbolo do hidrogênio:", ["H","He","Hi","Hg"], 0, "facil", "H", "UFMG 2009"),
            Q("(ENEM) Fórmula da água:", ["CO₂","H₂O","NaCl","O₂"], 1, "facil", "H₂O", "ENEM 2014"),
            Q("(UERJ) Estado físico do gelo:", ["Sólido","Líquido","Gasoso","Plasma"], 0, "facil", "Sólido", "UERJ 2010"),
            Q("(UFPR) Átomo é composto por:", ["Apenas prótons","Prótons, nêutrons e elétrons","Apenas elétrons","Moléculas"], 1, "facil", "p+, n⁰, e−", "UFPR 2011"),
            Q("(UFRJ) Símbolo do oxigênio:", ["Ox","O","O₂","On"], 1, "facil", "O", "UFRJ 2010"),
            Q("(UFMG) pH neutro vale:", ["0","7","14","-7"], 1, "facil", "pH = 7 → neutro", "UFMG 2012"),
        ],
        "intermediario": [
            Q("(FUVEST) Família 1A (alcalinos) inclui:", ["He, Ne","Li, Na, K","F, Cl","C, Si"], 1, "medio", "Metais alcalinos", "FUVEST 2012"),
            Q("(UNICAMP) NaCl tem ligação:", ["Covalente","Iônica","Metálica","Hidrogênio"], 1, "medio", "Sal: Na⁺ + Cl⁻", "UNICAMP 2014"),
            Q("(UERJ) Mol contém:", ["10²³","6,02×10²³","6,02×10¹⁰","10¹⁰"], 1, "medio", "Constante de Avogadro", "UERJ 2015"),
            Q("(UFMG) H₂O ferve, ao nível do mar, a:", ["50°C","100°C","120°C","80°C"], 1, "facil", "100°C a 1 atm", "UFMG 2013"),
            Q("(UFPR) HCl é um:", ["Ácido","Base","Sal","Óxido"], 0, "medio", "Ácido clorídrico", "UFPR 2014"),
            Q("(UFRJ) NaOH é uma:", ["Ácido","Base forte","Sal","Óxido"], 1, "medio", "Soda cáustica", "UFRJ 2014"),
        ],
        "avancado": [
            Q("(FUVEST) Função orgânica do etanol (CH₃CH₂OH):", ["Ácido","Álcool","Éter","Cetona"], 1, "medio", "Grupo OH", "FUVEST 2014"),
            Q("(UNICAMP) Reação exotérmica:", ["Absorve calor","Libera calor","Não troca","Apenas luz"], 1, "medio", "ΔH < 0", "UNICAMP 2015"),
            Q("(UERJ) Isomeria de C₂H₆O:", ["Etanol/éter dimetílico","Apenas CO₂","Apenas metano","Glicose"], 0, "dificil", "Mesma fórmula, funções diferentes", "UERJ 2018"),
            Q("(UFRJ) Reação ácido + base forma:", ["Apenas gás","Sal e água","Metal","Plástico"], 1, "medio", "Neutralização", "UFRJ 2017"),
            Q("(UFMG) Eletronegatividade maior:", ["Na","Cl","K","Mg"], 1, "dificil", "Cl entre os listados", "UFMG 2018"),
            Q("(UFPR) Hibridização do C no metano:", ["sp","sp²","sp³","p"], 2, "dificil", "4 ligações simples", "UFPR 2018"),
        ],
        "enem": [
            Q("(ENEM 2020) Lei de Lavoisier afirma:", ["Energia conservada","Massa conservada","Volume constante","Temperatura constante"], 1, "medio", "Massa total se conserva", "ENEM 2020"),
            Q("(ENEM 2019) Combustíveis fósseis liberam:", ["O₂","CO₂","N₂","H₂"], 1, "facil", "CO₂ → efeito estufa", "ENEM 2019"),
            Q("(ENEM 2021) Concentração mol/L é:", ["g/L","mol/L","mol·L","mol/g"], 1, "medio", "Molaridade", "ENEM 2021"),
            Q("(ENEM 2018) Eletrólise produz:", ["Calor apenas","Reação química por eletricidade","Som","Luz apenas"], 1, "medio", "Decomposição por corrente", "ENEM 2018"),
            Q("(ENEM 2022) Polímero artificial:", ["Algodão","Amido","Polietileno","Seda"], 2, "medio", "Plástico polietileno", "ENEM 2022"),
            Q("(ENEM 2017) pH < 7 indica solução:", ["Básica","Neutra","Ácida","Salina"], 2, "facil", "Ácida", "ENEM 2017"),
        ],
        "fuvest": [
            Q("(FUVEST 2019) Lei de Boyle relaciona:", ["P e V (T const)","V e T","P e T","Massa e V"], 0, "dificil", "P·V = const a T constante", "FUVEST 2019"),
            Q("(FUVEST 2020) Estequiometria envolve:", ["Apenas pH","Proporções em reações","Apenas eletrólise","Apenas radioatividade"], 1, "medio", "Cálculo de quantidades", "FUVEST 2020"),
            Q("(USP 2021) Hidrocarboneto saturado tem ligação:", ["Tripla","Dupla","Simples C-C","Iônica"], 2, "medio", "Apenas ligações simples", "USP 2021"),
            Q("(FUVEST 2018) Reação de combustão completa libera:", ["CO + H","CO₂ + H₂O","NH₃","SO₂"], 1, "medio", "Oxidação total", "FUVEST 2018"),
            Q("(FUVEST 2017) Le Chatelier prevê deslocamento de equilíbrio por:", ["Apenas calor","Pressão, temperatura, concentração","Apenas pressão","Apenas concentração"], 1, "dificil", "Princípio de Le Chatelier", "FUVEST 2017"),
            Q("(FUVEST 2015) 1 mol de gás ideal nas CNTP ocupa:", ["11,2 L","22,4 L","33,6 L","100 L"], 1, "dificil", "Volume molar nas CNTP", "FUVEST 2015"),
        ],
    },
    "Física": {
        "basico": [
            Q("(UFMG) Unidade de força no SI:", ["Joule","Newton","Watt","Pascal"], 1, "facil", "N (kg·m/s²)", "UFMG 2010"),
            Q("(ENEM) Velocidade média = ?", ["d×t","d/t","t/d","d+t"], 1, "facil", "Vm = Δs/Δt", "ENEM 2013"),
            Q("(UERJ) g (gravidade da Terra) ≈:", ["5","9,8","20","100"], 1, "facil", "9,8 m/s²", "UERJ 2011"),
            Q("(UFPR) Peso de um corpo:", ["P=m","P=mg","P=ma","P=mv"], 1, "facil", "P = m·g", "UFPR 2010"),
            Q("(UFRJ) 1ª Lei de Newton trata de:", ["F=ma","Inércia","Ação-reação","Gravitação"], 1, "facil", "Princípio da inércia", "UFRJ 2011"),
            Q("(UFMG) Som propaga em:", ["Vácuo","Sólido, líquido e gás","Apenas ar","Apenas água"], 1, "facil", "Precisa meio material", "UFMG 2012"),
        ],
        "intermediario": [
            Q("(FUVEST) Energia cinética é:", ["mgh","½mv²","mv","ma"], 1, "medio", "Ec = ½mv²", "FUVEST 2013"),
            Q("(UNICAMP) Trabalho (J) =", ["F·d","F/d","F+d","F²"], 0, "medio", "W = F·d·cos θ", "UNICAMP 2014"),
            Q("(UERJ) Lei de Ohm:", ["V=R/I","V=R·I","V=I/R","R=V·I"], 1, "medio", "V = R·I", "UERJ 2015"),
            Q("(UFMG) MRU significa:", ["Mov. Retilíneo Uniforme","Mov. Rápido Único","Massa Real","Maior Raio"], 0, "facil", "Velocidade constante", "UFMG 2014"),
            Q("(UFPR) Resistores em série:", ["1/R","R = R₁+R₂+...","R²","R/2"], 1, "medio", "Somam-se", "UFPR 2017"),
            Q("(ENEM) Energia potencial gravitacional:", ["½mv²","mgh","Fd","ma"], 1, "medio", "Ep = mgh", "ENEM 2017"),
        ],
        "avancado": [
            Q("(FUVEST) Comprimento de onda × frequência:", ["v=λf","v=λ/f","v=f/λ","v=λ+f"], 0, "medio", "v = λ·f", "FUVEST 2016"),
            Q("(UNICAMP) Lente convergente é:", ["Plana","Côncava","Convexa","Espelho"], 2, "medio", "Convexa converge raios", "UNICAMP 2018"),
            Q("(UERJ) Carga do elétron:", ["Positiva","Negativa","Neutra","Variável"], 1, "facil", "−e", "UERJ 2014"),
            Q("(UFRJ) Velocidade da luz no vácuo:", ["3·10⁵ m/s","3·10⁸ m/s","10⁶ m/s","10⁴ m/s"], 1, "medio", "c ≈ 3·10⁸ m/s", "UFRJ 2018"),
            Q("(UFMG) Efeito Doppler ocorre com:", ["Apenas luz","Movimento relativo de fonte/observador","Repouso","Apenas em líquidos"], 1, "dificil", "Deslocamento de frequência", "UFMG 2019"),
            Q("(UFPR) Capacitor armazena:", ["Calor","Carga elétrica","Som","Massa"], 1, "medio", "Energia em campo elétrico", "UFPR 2018"),
        ],
        "enem": [
            Q("(ENEM 2020) Energia mecânica conserva-se quando:", ["Há atrito","Sem forças dissipativas","Sempre","Em quedas com ar"], 1, "medio", "Sem atrito/dissipação", "ENEM 2020"),
            Q("(ENEM 2019) Painel fotovoltaico converte:", ["Som em luz","Luz em eletricidade","Calor em luz","Eletricidade em calor"], 1, "facil", "Efeito fotovoltaico", "ENEM 2019"),
            Q("(ENEM 2021) Espelho côncavo pode formar imagem:", ["Apenas virtual","Real ou virtual conforme posição","Sempre invertida","Sempre direita"], 1, "dificil", "Depende da posição do objeto", "ENEM 2021"),
            Q("(ENEM 2018) Resistência elétrica depende de:", ["Apenas voltagem","Comprimento, área e material","Apenas área","Cor"], 1, "medio", "R = ρL/A", "ENEM 2018"),
            Q("(ENEM 2022) Movimento harmônico simples (MHS) tem:", ["Velocidade constante","Aceleração proporcional ao deslocamento","Sem força","Trajetória aleatória"], 1, "dificil", "F = −kx", "ENEM 2022"),
            Q("(ENEM 2017) Pressão hidrostática aumenta com:", ["Profundidade","Altura","Cor da água","Largura do recipiente"], 0, "medio", "P = ρgh", "ENEM 2017"),
        ],
        "fuvest": [
            Q("(FUVEST 2019) Efeito fotoelétrico foi explicado por:", ["Newton","Einstein","Bohr","Maxwell"], 1, "dificil", "Einstein, Nobel 1921", "FUVEST 2019"),
            Q("(FUVEST 2020) 3ª Lei de Newton:", ["F=ma","Ação e reação","Inércia","Gravitação universal"], 1, "medio", "Forças mútuas iguais e opostas", "FUVEST 2020"),
            Q("(USP 2021) Calor específico da água é alto, o que implica:", ["Aquecer rápido","Aquecer devagar","Sem variação","Evaporar fácil"], 1, "dificil", "Resiste a mudanças de T", "USP 2021"),
            Q("(FUVEST 2018) Frequência em hertz mede:", ["Energia/tempo","Ciclos por segundo","Distância","Massa"], 1, "medio", "Hz = 1/s", "FUVEST 2018"),
            Q("(FUVEST 2017) Tensão de transformador eleva-se quando:", ["N₁>N₂","N₂>N₁","N₁=N₂","Não muda"], 1, "dificil", "Razão de espiras", "FUVEST 2017"),
            Q("(FUVEST 2015) Princípio de Pascal aplica-se em:", ["Termômetro","Prensa hidráulica","Espelho","Lente"], 1, "dificil", "Pressão se transmite igual em fluidos", "FUVEST 2015"),
        ],
    },
    "Literatura": {
        "basico": [
            Q("(UFMG) Quem escreveu 'Dom Casmurro'?", ["Drummond","Machado de Assis","Alencar","Bilac"], 1, "facil", "Machado, 1899", "UFMG 2010"),
            Q("(ENEM) Soneto possui ___ versos:", ["8","10","12","14"], 3, "facil", "14 versos", "ENEM 2013"),
            Q("(UERJ) Verso branco é aquele que:", ["Não tem rima","Não tem métrica","Está em branco","É curto"], 0, "facil", "Sem rima", "UERJ 2011"),
            Q("(UFPR) 'Iracema' é obra de:", ["José de Alencar","Castro Alves","Bilac","Drummond"], 0, "facil", "Romantismo indianista", "UFPR 2012"),
            Q("(UFRJ) Olavo Bilac é:", ["Romântico","Parnasiano","Modernista","Barroco"], 1, "facil", "'Príncipe dos poetas'", "UFRJ 2010"),
            Q("(UFMG) Gênero épico narra:", ["Sentimentos","Heróis e feitos","Diálogos","Argumentos"], 1, "facil", "Heróis", "UFMG 2011"),
        ],
        "intermediario": [
            Q("(FUVEST) Modernismo no Brasil começa em:", ["1900","1922","1945","1964"], 1, "medio", "Semana de Arte Moderna 1922", "FUVEST 2013"),
            Q("(UNICAMP) Drummond pertence à:", ["1ª geração modernista","2ª geração modernista","3ª geração","Romantismo"], 1, "medio", "Geração de 1930", "UNICAMP 2015"),
            Q("(UERJ) Realismo brasileiro caracteriza-se por:", ["Sentimental","Crítico, social, objetivo","Indianista","Religioso"], 1, "medio", "Análise social objetiva", "UERJ 2014"),
            Q("(UFMG) Clarice Lispector é da geração:", ["1ª modernista","2ª modernista","3ª modernista","Romantismo"], 2, "medio", "Pós-1945", "UFMG 2016"),
            Q("(UFPR) 'Vidas Secas' é de:", ["Jorge Amado","Graciliano Ramos","Drummond","Machado"], 1, "medio", "Graciliano, 1938", "UFPR 2015"),
            Q("(UFRJ) Barroco caracteriza-se por:", ["Equilíbrio","Conflitos e antíteses","Razão pura","Indianismo"], 1, "medio", "Dualismo, religiosidade", "UFRJ 2013"),
        ],
        "avancado": [
            Q("(FUVEST) 'Os Sertões' é de:", ["Machado","Euclides da Cunha","Drummond","Lispector"], 1, "dificil", "Euclides, 1902", "FUVEST 2014"),
            Q("(UNICAMP) Concretismo enfatiza:", ["Métrica","Forma visual","Personagens","Gramática"], 1, "dificil", "Poesia visual/espacial", "UNICAMP 2017"),
            Q("(UERJ) Guimarães Rosa escreveu:", ["Capitães de Areia","Grande Sertão: Veredas","Memórias","Iracema"], 1, "medio", "1956", "UERJ 2017"),
            Q("(UFMG) Arcadismo busca:", ["Cidade","Bucolismo","Guerra","Monarquia"], 1, "dificil", "Vida no campo, simplicidade", "UFMG 2018"),
            Q("(UFPR) 'Capitães da Areia' é de:", ["Drummond","Jorge Amado","Lispector","Bandeira"], 1, "medio", "Jorge Amado, 1937", "UFPR 2016"),
            Q("(UFRJ) Fernando Pessoa criou heterônimos como:", ["Apenas Alberto","Caeiro, Reis, Campos","Apenas Pessoa","Bilac"], 1, "dificil", "Múltiplos heterônimos", "UFRJ 2015"),
        ],
        "enem": [
            Q("(ENEM 2020) Manuel Bandeira é poeta:", ["Romântico","Modernista 1ª geração","Parnasiano","Barroco"], 1, "medio", "Geração de 22", "ENEM 2020"),
            Q("(ENEM 2019) 'Macunaíma' é de:", ["Drummond","Mário de Andrade","Bilac","Camões"], 1, "medio", "Modernista, 1928", "ENEM 2019"),
            Q("(ENEM 2021) Naturalismo é vertente do:", ["Romantismo","Realismo","Modernismo","Barroco"], 1, "dificil", "Aluísio Azevedo", "ENEM 2021"),
            Q("(ENEM 2018) Cordel é literatura:", ["Erudita","Popular nordestina","Paulista","Internacional"], 1, "facil", "Tradição oral nordestina", "ENEM 2018"),
            Q("(ENEM 2022) Cecília Meireles foi poeta:", ["Romântica","Modernista 2ª geração","Parnasiana","Árcade"], 1, "medio", "Geração de 1930", "ENEM 2022"),
            Q("(ENEM 2017) Romance regionalista do Nordeste tem como autor:", ["Machado","Graciliano Ramos","Bilac","Camões"], 1, "medio", "Vidas Secas", "ENEM 2017"),
        ],
        "fuvest": [
            Q("(FUVEST 2019) Camões escreveu:", ["Lusíadas","Iracema","Sermões","Os Sertões"], 0, "medio", "Os Lusíadas, 1572", "FUVEST 2019"),
            Q("(FUVEST 2020) Padre António Vieira foi:", ["Modernista","Barroco","Romântico","Concretista"], 1, "dificil", "Sermões barrocos", "FUVEST 2020"),
            Q("(USP 2021) 'Memórias Póstumas de Brás Cubas' é narrado por:", ["Personagem vivo","Defunto autor","Narrador onisciente","Animal"], 1, "dificil", "Narrador defunto", "USP 2021"),
            Q("(FUVEST 2018) Gregório de Matos foi poeta:", ["Modernista","Barroco","Romântico","Árcade"], 1, "dificil", "'Boca do Inferno'", "FUVEST 2018"),
            Q("(FUVEST 2017) 'Memórias de um Sargento de Milícias' é de:", ["Manuel Antônio de Almeida","Machado","Alencar","Bilac"], 0, "dificil", "1853", "FUVEST 2017"),
            Q("(FUVEST 2015) Tropicália na literatura/música teve como ícone:", ["Drummond","Caetano Veloso e Gilberto Gil","Machado","Bandeira"], 1, "medio", "Movimento dos anos 1960", "FUVEST 2015"),
        ],
    },
    "Inglês": {
        "basico": [
            Q("(UFMG) I ___ a student.", ["am","is","are","be"], 0, "facil", "I + am", "UFMG 2010"),
            Q("(ENEM) She ___ tall.", ["am","is","are","be"], 1, "facil", "She + is", "ENEM 2013"),
            Q("(UERJ) Past of 'go':", ["goed","went","gone","going"], 1, "facil", "Irregular: went", "UERJ 2011"),
            Q("(UFPR) 'Apple' = ", ["Banana","Maçã","Uva","Pera"], 1, "facil", "Apple = maçã", "UFPR 2012"),
            Q("(UFRJ) They ___ from Brazil.", ["am","is","are","be"], 2, "facil", "They + are", "UFRJ 2010"),
            Q("(UFMG) Plural of 'box':", ["boxs","boxes","boxen","box"], 1, "facil", "+es", "UFMG 2012"),
        ],
        "intermediario": [
            Q("(FUVEST) Present continuous of 'eat':", ["eat","eating","ate","eaten"], 1, "medio", "be + verb-ing", "FUVEST 2014"),
            Q("(UNICAMP) Plural of 'child':", ["childs","children","childes","child"], 1, "medio", "Irregular", "UNICAMP 2015"),
            Q("(UERJ) If I ___ rich, I would travel.", ["am","were","be","is"], 1, "medio", "2nd conditional", "UERJ 2016"),
            Q("(UFPR) Comparative of 'good':", ["gooder","more good","better","best"], 2, "medio", "Better", "UFPR 2017"),
            Q("(UFMG) Phrasal 'give up' = ", ["aumentar","desistir","dar","subir"], 1, "medio", "Desistir", "UFMG 2018"),
            Q("(UFRJ) Modal 'must' indica:", ["Possibilidade","Obrigação forte","Habilidade","Permissão"], 1, "medio", "Strong obligation", "UFRJ 2017"),
        ],
        "avancado": [
            Q("(FUVEST) Passive voice of 'They build houses':", ["Houses are built","Houses build","Houses being","Houses been"], 0, "medio", "are + past participle", "FUVEST 2016"),
            Q("(UNICAMP) 'Used to' indica:", ["Hábito presente","Hábito passado","Futuro","Imperativo"], 1, "dificil", "Past habits", "UNICAMP 2018"),
            Q("(UERJ) 'Despite' is followed by:", ["Verbo","Substantivo/-ing","Adjetivo só","Advérbio"], 1, "dificil", "Despite + noun/-ing", "UERJ 2018"),
            Q("(UFMG) Reading: main idea =", ["Detail","Gist","Quote","List"], 1, "dificil", "Gist = ideia central", "UFMG 2019"),
            Q("(UFPR) 'However' is a:", ["Coordinating conjunction","Adverb of contrast","Verb","Noun"], 1, "medio", "Conector de contraste", "UFPR 2018"),
            Q("(UFRJ) Pronome relativo para pessoas:", ["which","who","what","where"], 1, "medio", "Who para pessoas", "UFRJ 2018"),
        ],
        "enem": [
            Q("(ENEM 2020) 'Although' tem mesmo sentido de:", ["Because","Even though","So","If"], 1, "medio", "Embora / mesmo que", "ENEM 2020"),
            Q("(ENEM 2019) Texto sobre poluição: 'pollution' significa:", ["Limpeza","Poluição","Florestamento","Reciclagem"], 1, "facil", "Poluição", "ENEM 2019"),
            Q("(ENEM 2021) 'In order to' expressa:", ["Causa","Finalidade","Tempo","Lugar"], 1, "medio", "Para / a fim de", "ENEM 2021"),
            Q("(ENEM 2018) Verb tense 'have done' é:", ["Past simple","Present perfect","Future","Past perfect"], 1, "medio", "Have/has + past participle", "ENEM 2018"),
            Q("(ENEM 2022) 'Nevertheless' é sinônimo de:", ["Therefore","However","Because","So"], 1, "dificil", "Contraste", "ENEM 2022"),
            Q("(ENEM 2017) Reading: skim significa:", ["Detalhar","Ler superficial","Memorizar","Traduzir"], 1, "medio", "Leitura rápida", "ENEM 2017"),
        ],
        "fuvest": [
            Q("(FUVEST 2019) Reported speech of 'I am happy':", ["He said he is happy","He said he was happy","He says is happy","He said being happy"], 1, "dificil", "Tense backshift", "FUVEST 2019"),
            Q("(FUVEST 2020) Inversão para ênfase: 'Never have I ___'", ["see","saw","seen","seeing"], 2, "dificil", "Have/has + past participle", "FUVEST 2020"),
            Q("(USP 2021) Future perfect: 'By 2030 we ___ achieved...'", ["have","will have","had","were"], 1, "dificil", "will have + PP", "USP 2021"),
            Q("(FUVEST 2018) 'In spite of' é seguido por:", ["Verbo conjugado","Substantivo/-ing","Adjetivo isolado","Apenas pronomes"], 1, "dificil", "+ noun/gerund", "FUVEST 2018"),
            Q("(FUVEST 2017) Discourse marker 'on the other hand' indica:", ["Adição","Contraste","Causa","Consequência"], 1, "medio", "Por outro lado", "FUVEST 2017"),
            Q("(FUVEST 2015) 'Whereas' significa:", ["Assim","Enquanto que (contraste)","Por isso","Antes"], 1, "dificil", "Contraste/comparação", "FUVEST 2015"),
        ],
    },
}

ACHIEVEMENTS_SEED = [
    {"name": "Primeiro passo",  "description": "Complete sua primeira lição",         "icon": "Sparkles", "color": "#22C55E", "type": "lessons", "threshold": 1,  "order": 1},
    {"name": "Aluno dedicado",  "description": "Complete 5 lições",                    "icon": "BookOpen", "color": "#3B82F6", "type": "lessons", "threshold": 5,  "order": 2},
    {"name": "Maratonista",     "description": "Complete 15 lições",                   "icon": "Trophy",   "color": "#EAB308", "type": "lessons", "threshold": 15, "order": 3},
    {"name": "Estudioso",       "description": "Complete 30 lições",                   "icon": "BookMarked","color": "#EC4899","type": "lessons", "threshold": 30, "order": 4},
    {"name": "Iniciando a chama","description": "3 dias de ofensiva",                  "icon": "Flame",    "color": "#F97316", "type": "streak",  "threshold": 3,  "order": 5},
    {"name": "Pegando fogo",    "description": "7 dias de ofensiva",                   "icon": "Flame",    "color": "#EF4444", "type": "streak",  "threshold": 7,  "order": 6},
    {"name": "100 XP",          "description": "Acumule 100 XP",                       "icon": "Zap",      "color": "#EAB308", "type": "xp",      "threshold": 100,"order": 7},
    {"name": "500 XP",          "description": "Acumule 500 XP",                       "icon": "Star",     "color": "#8B5CF6", "type": "xp",      "threshold": 500,"order": 8},
    {"name": "1000 XP",         "description": "Acumule 1000 XP",                      "icon": "Stars",    "color": "#06B6D4", "type": "xp",      "threshold": 1000,"order": 9},
    {"name": "Perfeição",       "description": "Complete uma lição sem erros",         "icon": "Award",    "color": "#22C55E", "type": "perfect", "threshold": 1,  "order": 10},
    {"name": "Patente Prata",   "description": "Alcance Prata",                        "icon": "Award",    "color": "#94A3B8", "type": "rank",    "threshold": 1,  "order": 11},
    {"name": "Patente Ouro",    "description": "Alcance Ouro",                         "icon": "Trophy",   "color": "#EAB308", "type": "rank",    "threshold": 2,  "order": 12},
    {"name": "Patente Platina", "description": "Alcance Platina",                      "icon": "Gem",      "color": "#22D3EE", "type": "rank",    "threshold": 3,  "order": 13},
    {"name": "Patente Diamante","description": "Alcance Diamante",                     "icon": "Diamond",  "color": "#60A5FA", "type": "rank",    "threshold": 4,  "order": 14},
    {"name": "Sábio Lendário",  "description": "Alcance a patente máxima: Sábio",      "icon": "Crown",    "color": "#A855F7", "type": "rank",    "threshold": 5,  "order": 15},
]
